import type { KenyaFacility } from "@/types/medistock";

// Generated by scripts/extract-kenya-facilities.ts from data/raw/kenya-health-facilities.geojson
export const kenyaFacilities = [
  {
    "id": "kisumu-aga-khan-kibuye-medical-centre-8190853447",
    "name": "Aga Khan Kibuye Medical Centre",
    "facilityType": "Medical centre",
    "county": "Kisumu",
    "latitude": -0.0908445,
    "longitude": 34.7683729,
    "ownership": "Private",
    "services": [
      "Primary care",
      "Outpatient care",
      "Referral support"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-ahava-medical-center-8190977962",
    "name": "Ahava Medical Center",
    "facilityType": "Medical centre",
    "county": "Kisumu",
    "latitude": -0.0897917,
    "longitude": 34.78222,
    "ownership": "Private",
    "services": [
      "Primary care",
      "Outpatient care",
      "Referral support"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-ambundo-medical-centre-8190988759",
    "name": "Ambundo Medical Centre",
    "facilityType": "Medical centre",
    "county": "Kisumu",
    "latitude": -0.0803166,
    "longitude": 34.7465734,
    "ownership": "Private",
    "services": [
      "Primary care",
      "Outpatient care",
      "Referral support"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-benec-medical-centre-8190977178",
    "name": "BENEC Medical Centre",
    "facilityType": "Medical centre",
    "county": "Kisumu",
    "latitude": -0.0763367,
    "longitude": 34.7298083,
    "ownership": "Private",
    "services": [
      "Primary care",
      "Outpatient care",
      "Referral support"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-christelle-medical-center-8190963903",
    "name": "Christelle Medical Center",
    "facilityType": "Medical centre",
    "county": "Kisumu",
    "latitude": -0.088395,
    "longitude": 34.7775267,
    "ownership": "Private",
    "services": [
      "Primary care",
      "Outpatient care",
      "Referral support"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-fairmont-hosptial-11119145706",
    "name": "Fairmont hosptial",
    "facilityType": "Hospital",
    "county": "Kisumu",
    "latitude": -0.0874105,
    "longitude": 34.7689685,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-global-provider-intl-health-center-8190894304",
    "name": "Global Provider Intl Health Center",
    "facilityType": "Health centre",
    "county": "Kisumu",
    "latitude": -0.08824,
    "longitude": 34.7795433,
    "ownership": "Private",
    "services": [
      "Primary care",
      "Immunization",
      "Maternal health"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-guru-nanak-hospital-10941825182",
    "name": "Guru Nanak Hospital",
    "facilityType": "Hospital",
    "county": "Kisumu",
    "latitude": -0.1008349,
    "longitude": 34.7526192,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-home-community-medical-centre-8190992989",
    "name": "Home Community Medical Centre",
    "facilityType": "Medical centre",
    "county": "Kisumu",
    "latitude": -0.0928766,
    "longitude": 34.7855008,
    "ownership": "Private",
    "services": [
      "Primary care",
      "Outpatient care",
      "Referral support"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-joy-pediatric-medical-centre-8190794363",
    "name": "Joy Pediatric Medical Centre",
    "facilityType": "Medical centre",
    "county": "Kisumu",
    "latitude": -0.0979283,
    "longitude": 34.7656017,
    "ownership": "Private",
    "services": [
      "Primary care",
      "Outpatient care",
      "Referral support"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-kodiaga-sub-county-hospital-8190978362",
    "name": "Kodiaga Sub-County Hospital",
    "facilityType": "Hospital",
    "county": "Kisumu",
    "subCounty": "Bondeni",
    "addressOrArea": "Bondeni",
    "latitude": -0.0624,
    "longitude": 34.7085567,
    "ownership": "County Government",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-port-florence-hospital-8191008507",
    "name": "Port Florence Hospital",
    "facilityType": "Hospital",
    "county": "Kisumu",
    "latitude": -0.1312579,
    "longitude": 34.7446396,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-st-jairus-8190955390",
    "name": "St Jairus",
    "facilityType": "Hospital",
    "county": "Kisumu",
    "latitude": -0.0762983,
    "longitude": 34.7240517,
    "ownership": "Faith-based",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-star-hospital-8190812612",
    "name": "Star Hospital",
    "facilityType": "Hospital",
    "county": "Kisumu",
    "latitude": -0.0969162,
    "longitude": 34.7647115,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "kisumu-star-hospital-kisumu-annex-8190988798",
    "name": "Star Hospital Kisumu Annex",
    "facilityType": "Hospital",
    "county": "Kisumu",
    "latitude": -0.0841326,
    "longitude": 34.7896853,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-aga-khan-medical-center-changamwe-12687068519",
    "name": "Aga khan medical center changamwe",
    "facilityType": "Medical centre",
    "county": "Mombasa",
    "latitude": -4.0254594,
    "longitude": 39.6249509,
    "services": [
      "Primary care",
      "Outpatient care",
      "Referral support"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-ansari-hospital-12556066727",
    "name": "Ansari hospital",
    "facilityType": "Hospital",
    "county": "Mombasa",
    "latitude": -4.0101038,
    "longitude": 39.6033182,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-bokole-cdf-health-center-12584844421",
    "name": "bokole cdf health center",
    "facilityType": "Health centre",
    "county": "Mombasa",
    "latitude": -4.0170131,
    "longitude": 39.6087882,
    "services": [
      "Primary care",
      "Immunization",
      "Maternal health"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-bomu-hospital-12542069401",
    "name": "bomu hospital",
    "facilityType": "Hospital",
    "county": "Mombasa",
    "latitude": -4.0272174,
    "longitude": 39.6175187,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-bomu-hospital-nyali-6038796194",
    "name": "Bomu Hospital Nyali",
    "facilityType": "Hospital",
    "county": "Mombasa",
    "addressOrArea": "Mombasa",
    "latitude": -4.0461612,
    "longitude": 39.6972538,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-caresource-health-center-10246359622",
    "name": "Caresource health center",
    "facilityType": "Health centre",
    "county": "Mombasa",
    "latitude": -3.9535087,
    "longitude": 39.7474918,
    "services": [
      "Primary care",
      "Immunization",
      "Maternal health"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-equity-afya-medical-center-12704039843",
    "name": "Equity afya medical center",
    "facilityType": "Medical centre",
    "county": "Mombasa",
    "latitude": -4.0273769,
    "longitude": 39.6277114,
    "services": [
      "Primary care",
      "Outpatient care",
      "Referral support"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-gertrude-s-children-s-hospital-mombasa-3848602473",
    "name": "Gertrude's Children's Hospital Mombasa",
    "facilityType": "Hospital",
    "county": "Mombasa",
    "addressOrArea": "Mombasa",
    "latitude": -4.0320716,
    "longitude": 39.7116664,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-jocham-1795791432",
    "name": "Jocham",
    "facilityType": "Hospital",
    "county": "Mombasa",
    "addressOrArea": "Mombasa",
    "latitude": -4.0368289,
    "longitude": 39.6820435,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-mainland-health-center-13563447332",
    "name": "Mainland health center",
    "facilityType": "Health centre",
    "county": "Mombasa",
    "latitude": -4.0182802,
    "longitude": 39.6226717,
    "services": [
      "Primary care",
      "Immunization",
      "Maternal health"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-mikindani-hospital-12698129503",
    "name": "mikindani hospital",
    "facilityType": "Hospital",
    "county": "Mombasa",
    "latitude": -4.0069017,
    "longitude": 39.6283103,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-miritini-sheikh-said-juma-7598450585",
    "name": "Miritini Sheikh Said & Juma",
    "facilityType": "Hospital",
    "county": "Mombasa",
    "latitude": -4.0152876,
    "longitude": 39.5905229,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-mtwapa-public-hospital-10239675033",
    "name": "Mtwapa public hospital",
    "facilityType": "Hospital",
    "county": "Mombasa",
    "latitude": -3.9479717,
    "longitude": 39.7386642,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-plasma-medical-center-3848663084",
    "name": "Plasma Medical Center",
    "facilityType": "Hospital",
    "county": "Mombasa",
    "latitude": -4.0482213,
    "longitude": 39.6854076,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "mombasa-wauguzi-healthcare-11773404435",
    "name": "Wauguzi Healthcare",
    "facilityType": "Clinic",
    "county": "Mombasa",
    "subCounty": "Magogoni Ward",
    "addressOrArea": "Magogoni ward",
    "latitude": -4.0233133,
    "longitude": 39.6808114,
    "services": [
      "Primary care",
      "Vaccination",
      "Referral support"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-afrismart-group-of-hospitals-ltd-8415873217",
    "name": "Afrismart Group of Hospitals LTD",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "latitude": -1.3183412,
    "longitude": 36.8937074,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-aga-khan-hospital-komarock-6173489602",
    "name": "Aga Khan Hospital Komarock",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "addressOrArea": "Nairobi",
    "latitude": -1.2676453,
    "longitude": 36.9055678,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-aga-khan-university-hospital-greenspan-mall-clinic-8415831221",
    "name": "Aga Khan University Hospital - (Greenspan Mall Clinic)",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "latitude": -1.288816,
    "longitude": 36.9011334,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-aga-khan-university-hospital-medical-center-6210101303",
    "name": "Aga Khan University Hospital Medical Center",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "subCounty": "Syokimau",
    "addressOrArea": "Syokimau",
    "latitude": -1.3765098,
    "longitude": 36.9262854,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-aga-khan-university-hospital-medical-centre-5414008483",
    "name": "Aga Khan University Hospital Medical Centre",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "addressOrArea": "Nairobi",
    "latitude": -1.3009005,
    "longitude": 36.7877061,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-agakhan-university-hospital-valley-arcade-clinic-8415948117",
    "name": "Agakhan University Hospital Valley Arcade Clinic",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "latitude": -1.2614711,
    "longitude": 36.8205792,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-aic-kijabe-hospital-nairobi-medical-centre-8415951817",
    "name": "AIC Kijabe Hospital Nairobi Medical Centre",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "latitude": -1.2667439,
    "longitude": 36.7964808,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-al-khair-health-centre-7930787284",
    "name": "Al Khair Health Centre",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "latitude": -1.3088167,
    "longitude": 36.7761853,
    "ownership": "Cbo",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-alice-nursing-home-949598013",
    "name": "Alice Nursing Home",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "addressOrArea": "Nairobi",
    "latitude": -1.3144759,
    "longitude": 36.8844394,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-amua-family-health-clinic-7930813003",
    "name": "AMUA Family health Clinic",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "latitude": -1.3150767,
    "longitude": 36.7966933,
    "ownership": "Cbo",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-brightstar-medical-centre-8416012017",
    "name": "Brightstar Medical Centre",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "latitude": -1.284468,
    "longitude": 36.884371,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-bripa-hospital-12244073037",
    "name": "bripa hospital",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "latitude": -1.3107693,
    "longitude": 36.8720542,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-bristol-park-hospital-fedha-8120540042",
    "name": "Bristol Park Hospital - Fedha",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "latitude": -1.3132826,
    "longitude": 36.896595,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-bristol-park-hospital-fedha-8416025917",
    "name": "Bristol Park Hospital Fedha",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "latitude": -1.3130358,
    "longitude": 36.8923199,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-bristol-park-hospital-utawala-8416046117",
    "name": "Bristol Park Hospital Utawala",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "latitude": -1.279414,
    "longitude": 36.965066,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-health-gate-hospital-8429563117",
    "name": "Health Gate Hospital",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "addressOrArea": "Nairobi",
    "latitude": -1.2796498,
    "longitude": 36.8461108,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-mariakani-cottage-hospital-6210121906",
    "name": "Mariakani Cottage Hospital",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "subCounty": "Mlolongo",
    "addressOrArea": "Mlolongo",
    "latitude": -1.3909021,
    "longitude": 36.934438,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-mercilin-afya-centre-7930812998",
    "name": "Mercilin Afya Centre",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "addressOrArea": "Nairobi",
    "latitude": -1.3129604,
    "longitude": 36.7843818,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-st-peters-orthopedic-surgical-sepcialty-center-ltd-11268942082",
    "name": "St Peters Orthopedic & Surgical Sepcialty Center Ltd",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "subCounty": "Kiambu",
    "addressOrArea": "Kiambu",
    "latitude": -1.2524111,
    "longitude": 36.6862035,
    "ownership": "Public",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination",
      "Dental care"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "nairobi-the-mater-hospital-satellite-clinic-trm-3289275202",
    "name": "The Mater Hospital - Satellite Clinic(TRM)",
    "facilityType": "Hospital",
    "county": "Nairobi",
    "addressOrArea": "Nairobi",
    "latitude": -1.2198096,
    "longitude": 36.8889635,
    "ownership": "Faith-based",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "turkana-aic-10864747462",
    "name": "AIC",
    "facilityType": "Hospital",
    "county": "Turkana",
    "latitude": 3.7551695,
    "longitude": 34.7503434,
    "ownership": "NGO",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "turkana-bliss-medical-centre-10864747448",
    "name": "Bliss Medical Centre",
    "facilityType": "Medical centre",
    "county": "Turkana",
    "latitude": 3.7086577,
    "longitude": 34.8650925,
    "ownership": "Private",
    "services": [
      "Primary care",
      "Outpatient care",
      "Referral support"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "turkana-goodlife-pharmacy-health-beauty-10864747456",
    "name": "Goodlife Pharmacy Health Beauty.",
    "facilityType": "Pharmacy",
    "county": "Turkana",
    "subCounty": "Kakuma",
    "addressOrArea": "Kakuma",
    "latitude": 3.7106344,
    "longitude": 34.8556837,
    "ownership": "Private",
    "services": [
      "Dispensing",
      "Health information",
      "Referral support"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "turkana-kalobeyei-main-medical-centre-10864747465",
    "name": "Kalobeyei Main Medical Centre",
    "facilityType": "Hospital",
    "county": "Turkana",
    "latitude": 3.7696051,
    "longitude": 34.7292905,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "turkana-lodwar-county-referral-hospital-10876458964",
    "name": "Lodwar County Referral Hospital",
    "facilityType": "Hospital",
    "county": "Turkana",
    "subCounty": "Lodwar",
    "addressOrArea": "Lodwar",
    "latitude": 3.1223431,
    "longitude": 35.6024292,
    "ownership": "Government",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "turkana-nakwamoru-health-centre-10865401647",
    "name": "Nakwamoru Health Centre",
    "facilityType": "Hospital",
    "county": "Turkana",
    "subCounty": "Nakwamoru",
    "addressOrArea": "Nakwamoru",
    "latitude": 2.0557489,
    "longitude": 35.4313988,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "turkana-nationakar-desp-10864747436",
    "name": "Nationakar Desp",
    "facilityType": "Hospital",
    "county": "Turkana",
    "latitude": 3.7574504,
    "longitude": 34.811562,
    "ownership": "NGO",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "turkana-natukobenyo-health-centre-10864747444",
    "name": "Natukobenyo Health Centre",
    "facilityType": "Hospital",
    "county": "Turkana",
    "latitude": 3.7744317,
    "longitude": 34.7308655,
    "ownership": "NGO",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "turkana-saint-elizabeth-lorugum-health-centre-10865168176",
    "name": "Saint Elizabeth Lorugum Health Centre",
    "facilityType": "Hospital",
    "county": "Turkana",
    "subCounty": "Lorugum",
    "addressOrArea": "Lorugum",
    "latitude": 2.8923531,
    "longitude": 35.2629953,
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  },
  {
    "id": "turkana-shepherds-hospital-10864747457",
    "name": "Shepherds Hospital",
    "facilityType": "Hospital",
    "county": "Turkana",
    "subCounty": "Kakuma",
    "addressOrArea": "Kakuma",
    "latitude": 3.7106229,
    "longitude": 34.8555924,
    "ownership": "Private",
    "services": [
      "Outpatient care",
      "Maternal health",
      "Vaccination"
    ],
    "source": "HOTOSM Kenya Health Facilities"
  }
] satisfies KenyaFacility[];
